name: Build Web App
 
on:
  push:
    branches: [ master ]
 
jobs:
  build:
 
    runs-on: windows-latest
 
    steps:
    - uses: actions/checkout@v1
      name: Checkout Code
     
    - name: Setup MSBuild Path
      uses: microsoft/setup-msbuild@v1
       
    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.5
     
    - name: Restore NuGet Packages
      run: nuget restore mvcnetwebapp.sln
 
    - name: Build and Publish Web App
      run: msbuild mvcnetwebapp.sln /p:Configuration=Release /p:DeployOnBuild=true /p:PublishProfile=FolderProfile
 
    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: published_webapp
        path: D:\a\mvcnetwebapp\mvcnetwebapp\mvcnetwebapp\bin\Release\Publish\
    
  notify:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: trigger single Job
      uses: appleboy/jenkins-action@master
      with:
        url: " https://1aeb-223-226-68-92.ngrok.io"
        user: "jijo"
        token: 11a8ff84c8ed1bde69f3e1cd48f95dd5a4
        job: "testBuild"
