name: Build Web App
 
on: [push]
 
jobs:
  build:
 
    runs-on: windows-latest
 
    steps:
    - uses: actions/checkout@v1
      name: Checkout Code
     
    - name: Setup MSBuild Path
      uses: microsoft/setup-msbuild@v1
       
    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.5
     
    - name: Restore NuGet Packages
      run: nuget restore mvcnetwebapp.sln
 
    - name: Build and Publish Web App
      run: msbuild mvcnetwebapp.sln /p:Configuration=Release /p:DeployOnBuild=true /p:PublishProfile=FolderProfile
 
    - name: Upload Artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: published_webapp
        path: ./bin/Release/Publish
    - name: FTP Deploy
      uses: SamKirkland/FTP-Deploy-Action@3.0.0
      with:
        # Deployment destination server & path. Formatted as protocol://domain.com:port/full/destination/path/
        ftp-server: ${{ secrets.FTP_SERVER }}
        # FTP account username
        ftp-username: ${{ secrets.FTP_USERNAME }}
        # FTP account password
        ftp-password: ${{ secrets.FTP_PASSWORD }}
        # The local folder to copy, defaults to root project folder
        local-dir:  bin\Release\Publish
